services:
  - type: web
    name: fitblendz-pro
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput --clear && python manage.py migrate && python manage.py populate_services && python manage.py populate_working_hours && python manage.py fix_admin
    startCommand: gunicorn fitblendz_pro.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://fitblendz-pro.onrender.com,https://*.onrender.com"
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: WHATSAPP_TOKEN
        value: "your_whatsapp_token_here"
      - key: PHONE_NUMBER_ID
        value: "your_phone_number_id_here"
      - key: WHATSAPP_VERIFY_TOKEN
        value: "fitblendz_whatsapp_verify_7c2f4b1e"
      - key: BARBER_WHATSAPP
        value: "+916239514954"
      - key: EMAIL_HOST_USER
        value: "bjot404@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        value: "pane gfwn gggh nqkr"
      - key: DEFAULT_FROM_EMAIL
        value: "bjot404@gmail.com"